export const PROTOBUF_ROOT = 'PROTOBUF_ROOT';

export const PB_ORDER_EVENT = 'PB_ORDER_EVENT';
export const PB_ORDER_CREATED = 'PB_ORDER_CREATED';
export const PB_PAYMENT_PROCESSED = 'PB_PAYMENT_PROCESSED';
export const PB_ORDER_CONFIRMED = 'PB_ORDER_CONFIRMED';
export const PB_ORDER_FAILED = 'PB_ORDER_FAILED';
